apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-reader-binding
  namespace: kk-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ns-reader
subjects:
  - kind: ServiceAccount
    name: kk-svc
    namespace: kk-ns