kind: ConfigMap
apiVersion: v1
metadata:
  name: spring-k8s-configmap-demo
  namespace: kk-ns
  labels:
    app: spring-k8s-configmap-demo
data:
  application.yml: |-
    greeting:
      message: Say Hello to the World
    ---
    spring:
      profiles: development
    greeting:
      message: Say Hello to the Developers
    ---
    spring:
      profiles: production
    greeting:
      message: Say Hello to the Ops