apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: spring-k8s-configmap-demo
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 130.211.40.129/32
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 80
    - from:
        - namespaceSelector: {}
        - podSelector: {}
