apiVersion: v1
kind: Service
metadata:
  name: spring-k8s-configmap-demo
  namespace: kk-ns
spec:
  selector:
    app: spring-k8s-configmap-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
  externalTrafficPolicy: Cluster